server:
  port: 8090
  servlet:
    context-path: /

# 数据源
spring:

  data:
    mongodb:
      uri: mongodb://yxr:rxh2019@192.168.1.111:27017/internal_playment

  datasource:
    username: root
    password: rxh@2019
#    url: jdbc:mysql://192.168.1.68/new_cross?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.1.68/internal_playment?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 50
    minIdle: 50
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # jackson时间格式化
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.rongxinhui.pay.inland.into.pay.into.test.api.entity
  #  typeEnumsPackage: com.rongxinhui.pay.inland.into.pay.into.test.api.entity.enums
  #  global-config:
  #    id-type: 2
  #    field-strategy: 2
  #    db-column-underline: true
  #    refresh-mapper: true
  #    #capital-mode: true
  #    #key-generator: com.baomidou.springboot.xxx
  #    logic-delete-value: 0
  #    logic-not-delete-value: 1
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #meta-object-handler: com.baomidou.springboot.xxx
  #    #sql-injector: com.baomidou.springboot.xxx
  #  configuration:
  #    map-underscore-to-camel-case: true
  #    cache-enabled: false
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true #使用驼峰命名
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

